import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "GapWalk Terms of Service | Sadik Yamin",
  description:
    "Terms of Service for GapWalk — a schedule-aware micro-walking app. Covers acceptable use, Google Calendar integration, disclaimers, and liability.",
};

const EFFECTIVE_DATE = "March 13, 2025";
const SUPPORT_EMAIL = "syam46484@gmail.com";

export default function GapWalkTermsPage() {
  return (
    <article className="py-12 sm:py-16 md:py-20">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <Link
          href="/projects/gapwalk"
          className="inline-flex items-center gap-1 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          GapWalk
        </Link>

        <header className="mt-6 sm:mt-8">
          <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-muted-foreground sm:mt-4">
            Effective Date: {EFFECTIVE_DATE} &nbsp;&middot;&nbsp; Last Updated:{" "}
            {EFFECTIVE_DATE}
          </p>
        </header>

        <Separator className="my-8 sm:my-10" />

        <div className="space-y-0">
          <p className="mb-4 leading-7 text-muted-foreground">
            Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully
            before using GapWalk (&ldquo;the App&rdquo;). By downloading,
            installing, or using GapWalk, you agree to be bound by these Terms.
          </p>

          {/* Section 1 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            1. Acceptance of Terms
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            By using GapWalk, you confirm that you are at least 13 years of age
            and that you agree to these Terms and our{" "}
            <Link
              href="/projects/gapwalk/privacy"
              className="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
            >
              Privacy Policy
            </Link>
            . If you do not agree, do not use the App.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 2 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            2. Description of Service
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            GapWalk is a mobile application that connects to your Google
            Calendar to identify short free windows in your daily schedule and
            remind you to take brief walks during those windows. The App is
            provided for personal, non-commercial use.
          </p>
          <p className="mb-4 leading-7 text-muted-foreground">
            GapWalk is not a medical device and does not provide medical advice.
            Walking suggestions generated by the App are based solely on your
            calendar availability and are not tailored to any health condition.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 3 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            3. User Responsibilities
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            By using GapWalk, you agree to:
          </p>
          <ul className="mb-4 ml-6 list-disc space-y-1 text-muted-foreground">
            <li className="leading-7">
              Provide accurate information when signing in with your Google
              account
            </li>
            <li className="leading-7">
              Use the App only for personal, lawful purposes
            </li>
            <li className="leading-7">
              Not attempt to reverse engineer, decompile, or modify the App
            </li>
            <li className="leading-7">
              Not use the App in any way that could harm other users, third
              parties, or the integrity of the Google Calendar API
            </li>
          </ul>
          <p className="mb-4 leading-7 text-muted-foreground">
            You are responsible for maintaining the security of your Google
            account. GapWalk is not responsible for unauthorized access to your
            account that results from your failure to secure your credentials.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 4 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            4. Acceptable Use
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            You may not use GapWalk to:
          </p>
          <ul className="mb-4 ml-6 list-disc space-y-1 text-muted-foreground">
            <li className="leading-7">
              Violate any applicable law or regulation
            </li>
            <li className="leading-7">
              Interfere with or disrupt the App or connected services
            </li>
            <li className="leading-7">
              Attempt to gain unauthorized access to any part of the App or
              connected services
            </li>
            <li className="leading-7">
              Collect or harvest information from other users
            </li>
            <li className="leading-7">
              Use the App for any commercial purpose without prior written
              consent
            </li>
          </ul>

          <Separator className="my-8 border-border/60" />

          {/* Section 5 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            5. Intellectual Property
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            All content, design, code, and branding in GapWalk are owned by or
            licensed to the developer of GapWalk. You are granted a limited,
            non-exclusive, non-transferable license to use the App for personal
            purposes on your own device.
          </p>
          <p className="mb-4 leading-7 text-muted-foreground">
            You may not reproduce, distribute, or create derivative works based
            on the App or its content without explicit permission.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 6 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            6. Google Services
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            GapWalk relies on the Google Calendar API, which is subject to{" "}
            <a
              href="https://policies.google.com/terms"
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
            >
              Google&apos;s Terms of Service
            </a>
            . Your use of the Google sign-in flow and calendar integration is
            also governed by Google&apos;s terms. GapWalk is not affiliated with
            or endorsed by Google LLC.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 7 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            7. Disclaimers
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            GapWalk is provided &ldquo;as is&rdquo; and &ldquo;as
            available&rdquo; without warranties of any kind, either express or
            implied, including but not limited to:
          </p>
          <ul className="mb-4 ml-6 list-disc space-y-1 text-muted-foreground">
            <li className="leading-7">
              Warranties of merchantability or fitness for a particular purpose
            </li>
            <li className="leading-7">
              Guarantees that the App will be uninterrupted, error-free, or
              always available
            </li>
            <li className="leading-7">
              Guarantees that calendar gap detection will be accurate at all
              times
            </li>
          </ul>
          <p className="mb-4 leading-7 text-muted-foreground">
            The accuracy of gap detection depends on the completeness and
            currency of your Google Calendar data. GapWalk is not responsible
            for missed gaps or incorrect availability calculations resulting from
            calendar data that is incomplete or not yet synced.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 8 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            8. Limitation of Liability
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            To the maximum extent permitted by applicable law, GapWalk and its
            developer shall not be liable for:
          </p>
          <ul className="mb-4 ml-6 list-disc space-y-1 text-muted-foreground">
            <li className="leading-7">
              Any indirect, incidental, special, consequential, or punitive
              damages
            </li>
            <li className="leading-7">
              Any loss of data, revenue, or goodwill
            </li>
            <li className="leading-7">
              Any injury or health condition resulting from walking or other
              physical activity undertaken in connection with the App
            </li>
          </ul>
          <p className="mb-4 leading-7 text-muted-foreground">
            Any liability arising from your use of GapWalk is limited to the
            amount you paid, if anything, to download or use the App.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 9 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            9. Termination
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            We reserve the right to terminate or suspend your access to GapWalk
            at any time if we reasonably believe you have violated these Terms.
            You may stop using the App and delete it from your device at any
            time, which constitutes termination of your use.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 10 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            10. Changes to the Service
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            We may update, modify, or discontinue GapWalk or any of its features
            at any time, with or without notice. We are not liable to you or any
            third party for any modification, suspension, or discontinuation of
            the App.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 11 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            11. Changes to These Terms
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            We may revise these Terms from time to time. The updated version
            will be posted with a new effective date. Your continued use of the
            App after any changes constitutes acceptance of the revised Terms.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 12 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            12. Governing Law
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            These Terms shall be governed by and construed in accordance with
            the laws of the State of Missouri, United States, without regard to
            conflict of law principles.
          </p>

          <Separator className="my-8 border-border/60" />

          {/* Section 13 */}
          <h2 className="mt-10 mb-4 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            13. Contact Information
          </h2>
          <p className="mb-4 leading-7 text-muted-foreground">
            If you have questions about these Terms, please contact us:
          </p>
          <p className="mb-4 leading-7 text-muted-foreground">
            <strong className="font-semibold text-foreground">Email:</strong>{" "}
            <a
              href={`mailto:${SUPPORT_EMAIL}`}
              className="font-medium text-primary underline underline-offset-4 hover:text-primary/80"
            >
              {SUPPORT_EMAIL}
            </a>
          </p>
        </div>

        <Separator className="my-8 sm:my-10" />

        <footer className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground">
          <Link
            href="/projects/gapwalk"
            className="transition-colors hover:text-foreground"
          >
            GapWalk
          </Link>
          <span aria-hidden="true">&middot;</span>
          <Link
            href="/projects/gapwalk/privacy"
            className="transition-colors hover:text-foreground"
          >
            Privacy Policy
          </Link>
          <span aria-hidden="true">&middot;</span>
          <span>GapWalk is not affiliated with or endorsed by Google LLC.</span>
        </footer>
      </div>
    </article>
  );
}
